version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: 
          name: Run installer
          command: .\installer.bat
      - run: 
          name: Service status
          command: nssm status SmartBambooApiService
      - run:
          name: Test open port
          command: telnet localhost PORTNUMBER

workflows:
  tests:
    jobs:
      - build
