version: 2.1

jobs:
  run-installer:
    docker:
      - image: mcr.microsoft.com/windows:ltsc2019
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "cmd.exe dir"

workflows:
  tests:
    jobs:
      - run-installer
