version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: .\installer.bat
      - run: cat C:\SB_Service\logs\service.log
      - run: cat C:\SB_Service\logs\service_error.log
      - run: nssm status SmartBambooApiService

workflows:
  tests:
    jobs:
      - build
