version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: dir
      - run: python --version
      - run: installer.bat

workflows:
  tests:
    jobs:
      - build
